group = input('Введите номер группы:')
name = input('Введите имя:')
s_name = input('Введите фамилию:')
f_name = input('Введите отчество:')
t_len = len(name) + len(s_name) + len(f_name)
l_name_lw = len('Лабораторная работа № 1')
r_group = len('Выполнил(а): ст. гр.') + len(group)
if t_len >= l_name_lw >= r_group:
    print('*' * (t_len + 4))
    print('*', 'Лабораторная работа № 1', '*')
    print('*', 'Выполнил(а): ст. гр.', group, '*')
    print('*', name, s_name, f_name, '*')
    print('*' * (t_len + 4))
elif l_name_lw >= t_len >= r_group:
    print('*' * (l_name_lw + 4))
    print('*', 'Лабораторная работа № 1', '*')
    print('*', 'Выполнил(а): ст. гр.', group, '*')
    print('*', name, s_name, f_name, '*')
    print('*' * (l_name_lw + 4))
elif r_group >= l_name_lw >= t_len:
    print('*' * (r_group + 4))
    print('*', 'Лабораторная работа № 1', '*')
    print('*', 'Выполнил(а): ст. гр.', group, '*')
    print('*', name, s_name, f_name, '*')
    print('*' * (r_group + 4))
